const MAX_PRODUCTS_PER_BUSINESS = 100;
const MAX_PRODUCT_PHOTOS = 3;
const MAX_PRODUCT_PHOTO_BYTES = 3 * 1024 * 1024;
const MAX_CART_LINES = 30;
const MAX_LINE_QTY = 99;

const COMMERCE_ORDER_STATUS = {
  PENDING_PAYMENT: 'pending_payment',
  CONFIRMED: 'confirmed',
  PREPARING: 'preparing',
  READY: 'ready',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  EXPIRED: 'expired',
};

// Vendor can only advance along this chain after payment.
const VENDOR_STATUS_FLOW = {
  [COMMERCE_ORDER_STATUS.CONFIRMED]: [COMMERCE_ORDER_STATUS.PREPARING],
  [COMMERCE_ORDER_STATUS.PREPARING]: [COMMERCE_ORDER_STATUS.READY],
  [COMMERCE_ORDER_STATUS.READY]: [COMMERCE_ORDER_STATUS.COMPLETED],
};

module.exports = {
  MAX_PRODUCTS_PER_BUSINESS,
  MAX_PRODUCT_PHOTOS,
  MAX_PRODUCT_PHOTO_BYTES,
  MAX_CART_LINES,
  MAX_LINE_QTY,
  COMMERCE_ORDER_STATUS,
  VENDOR_STATUS_FLOW,
};
