steps:
  # ── BUILD IMAGE ─────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: build-backend
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/ruxstar-backend/ruxstar-backend-services:$BUILD_ID
      - .

  # ── PUSH IMAGE ───────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: push-backend
    waitFor: [build-backend]
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/ruxstar-backend/ruxstar-backend-services:$BUILD_ID

  # ── DEPLOY TO CLOUD RUN ──────────────────────
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-backend
    waitFor: [push-backend]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ruxstar-backend-services
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/ruxstar-backend/ruxstar-backend-services:$BUILD_ID
      - --region=us-central1
      - --platform=managed
      - --port=8080
      - --allow-unauthenticated
      - --service-account=backend-service-account@ruxstar-platform.iam.gserviceaccount.com
      - --set-secrets=MONGODB_URI=mongodb-uri:latest
      - --quiet

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/ruxstar-backend/ruxstar-backend-services:$BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY