/** Default business catalog — inserted once when collections are empty. */

const BUSINESS_CATEGORIES = [
  {
    id: 'events',
    label: 'Events and tournaments',
    description: 'Sell tickets and manage live events',
    icon: '🎬',
    sortOrder: 0,
  },
  {
    id: 'bookings',
    label: 'Bookings & venues',
    description: 'Rent slots, courts, turf, or venue time',
    icon: '🏟️',
    sortOrder: 1,
  },
  {
    id: 'appointments',
    label: 'Appointments & wellness',
    description: 'Salons, clinics, consultations by calendar',
    icon: '💆',
    sortOrder: 2,
  },
  {
    id: 'print',
    label: 'Print on demand',
    description: 'Custom printing, merchandise & branding on order',
    icon: '🖨️',
    sortOrder: 3,
  },
  {
    id: 'commerce',
    label: 'Shopping & commerce',
    description: 'Sell physical or digital products online',
    icon: '🛍️',
    sortOrder: 4,
  },
  {
    id: 'creator',
    label: 'Creator economy',
    description: 'Content, merch, memberships, influencer offerings',
    icon: '✨',
    sortOrder: 5,
  },
];

const BUSINESS_TYPES = [
  {
    id: 'concert',
    categoryId: 'events',
    label: 'Concerts & live shows',
    description: 'Live events, festivals, performances',
    examples: 'Concert hall, event organiser',
    namePlaceholder: 'e.g. Live Arena',
    detailHint: 'Describe your venue or brand. Event listings come after onboarding.',
    module: 'events',
    sortOrder: 0,
  },
  {
    id: 'sports_event',
    categoryId: 'events',
    label: 'Sports events',
    description: 'Matches, tournaments, ticketed sports',
    examples: 'Stadium, sports club events',
    namePlaceholder: 'e.g. Champions Turf Events',
    detailHint: 'Your organisation name and where events are held.',
    module: 'events',
    sortOrder: 1,
  },
  {
    id: 'turf',
    categoryId: 'bookings',
    label: 'Sports turf & courts',
    description: 'Hourly slot booking for play areas',
    examples: 'Football turf, badminton court',
    namePlaceholder: 'e.g. Green Field Turf',
    detailHint: 'Venue name and address help customers find you for slot booking.',
    module: 'appointments',
    sortOrder: 0,
  },
  {
    id: 'venue',
    categoryId: 'bookings',
    label: 'Party & event venues',
    description: 'Banquet halls, studios, rent-by-slot',
    examples: 'Banquet hall, photo studio',
    namePlaceholder: 'e.g. Skyline Banquets',
    detailHint: 'How customers will recognise your venue on Ruxstar.',
    module: 'appointments',
    sortOrder: 1,
  },
  {
    id: 'salon',
    categoryId: 'appointments',
    label: 'Salon & spa',
    description: 'Hair, beauty, spa appointments',
    examples: 'Salon, spa, barbershop',
    namePlaceholder: 'e.g. Glow Salon',
    detailHint: "You'll add services and staff availability after this step.",
    module: 'appointments',
    sortOrder: 0,
  },
  {
    id: 'clinic',
    categoryId: 'appointments',
    label: 'Clinic & consultation',
    description: 'Medical or professional consultations',
    examples: 'Clinic, dental, therapy',
    namePlaceholder: 'e.g. Care Clinic',
    detailHint: 'Clinic or practice name as patients will see it.',
    module: 'appointments',
    sortOrder: 1,
  },
  {
    id: 'coaching',
    categoryId: 'appointments',
    label: 'Coaching & classes',
    description: 'Tutoring, fitness, skill coaching',
    examples: 'Tuition, yoga, music class',
    namePlaceholder: 'e.g. Ace Coaching',
    detailHint: 'Your coaching brand or academy name.',
    module: 'appointments',
    sortOrder: 2,
  },
  {
    id: 'print_shop',
    categoryId: 'print',
    label: 'Print Shop',
    description: 'General print shop — apparel, cards, banners & more',
    examples: 'Local printers, digital press',
    namePlaceholder: 'e.g. City Print Hub',
    detailHint: "You'll pick the print categories you serve and your area after this step.",
    module: 'print',
    sortOrder: 0,
  },
  {
    id: 'custom_merch',
    categoryId: 'print',
    label: 'Custom Merchandise Store',
    description: 'Made-to-order apparel and merchandise',
    examples: 'T-shirts, hoodies, mugs',
    namePlaceholder: 'e.g. MerchMakers',
    detailHint: 'Choose the products you print and where you deliver.',
    module: 'print',
    sortOrder: 1,
  },
  {
    id: 'creator_merch',
    categoryId: 'print',
    label: 'Creator Merchandise Store',
    description: 'Print & fulfil merch for creators and fans',
    examples: 'Fan merch, influencer drops',
    namePlaceholder: 'e.g. Creator Merch Co',
    detailHint: 'Set the merch categories you fulfil and your service area.',
    module: 'print',
    sortOrder: 2,
  },
  {
    id: 'corporate_printing',
    categoryId: 'print',
    label: 'Corporate Printing',
    description: 'Bulk corporate branding and stationery',
    examples: 'Business cards, corporate gifts',
    namePlaceholder: 'e.g. Corporate Print Works',
    detailHint: 'Pick the corporate products you handle and your coverage.',
    module: 'print',
    sortOrder: 3,
  },
  {
    id: 'event_printing',
    categoryId: 'print',
    label: 'Event Printing',
    description: 'Print for events — banners, invites, standees',
    examples: 'Wedding invites, event flex',
    namePlaceholder: 'e.g. EventPrint Studio',
    detailHint: 'Select the event materials you print and your area.',
    module: 'print',
    sortOrder: 4,
  },
  {
    id: 'branding_agency',
    categoryId: 'print',
    label: 'Branding Agency',
    description: 'Design + print for brand identity and promo',
    examples: 'Logo merch, promo kits',
    namePlaceholder: 'e.g. BrandCraft Agency',
    detailHint: 'Choose the branding products you deliver and your coverage.',
    module: 'print',
    sortOrder: 5,
  },
  {
    id: 'retail',
    categoryId: 'commerce',
    label: 'Retail shop',
    description: 'Physical store selling products',
    examples: 'Boutique, grocery, electronics',
    namePlaceholder: 'e.g. Urban Style Store',
    detailHint: 'Store name and location. Product catalog comes next.',
    module: 'commerce',
    sortOrder: 0,
  },
  {
    id: 'online_store',
    categoryId: 'commerce',
    label: 'Online store',
    description: 'E-commerce, delivery, pan-India',
    examples: 'D2C brand, marketplace seller',
    namePlaceholder: 'e.g. Ruxstar Merch',
    detailHint: 'Brand name customers see at checkout.',
    module: 'commerce',
    sortOrder: 1,
  },
  {
    id: 'creator',
    categoryId: 'creator',
    label: 'Creator / influencer',
    description: 'Content, community, digital offerings',
    examples: 'YouTuber, streamer, educator',
    namePlaceholder: 'e.g. Your channel or brand name',
    detailHint: 'Public name for your creator storefront.',
    module: 'creator',
    sortOrder: 0,
  },
  {
    id: 'digital_products',
    categoryId: 'creator',
    label: 'Digital products',
    description: 'Courses, templates, downloads',
    examples: 'Online course, presets, ebooks',
    namePlaceholder: 'e.g. Learn With Me',
    detailHint: 'Brand for your digital product line.',
    module: 'creator',
    sortOrder: 1,
  },
];

module.exports = { BUSINESS_CATEGORIES, BUSINESS_TYPES };
